version: '3'

networks:
  api-network:
    driver: bridge
volumes:
  mongo-vol:

services:
  mongodb:
    image: mongo
    volumes:
      - 'mongo-vol:/data/db'
    networks:
      - 'api-network'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    ports:
      - 27017:27017

  api:
    image: danilosv123/api-produto:latest
    environment:
      MONGODB_URI: mongodb
    networks:
      - api-network
    ports:
      - 8080:8080
    depends_on:
      - 'mongodb'      



